### ISSUE TITLE
Query parameter parser fails to parse array parameters correctly

### ISSUE THREAD

**Issue by uglyog** [BigstickCarpet/swagger-express-middleware#116]
The query parameter parser fails to parse query parameters in array CSV form (e.g. `q=1,2,3`). 

With the following OpenAPI 3.0 parameter definition:

```yaml
      parameters:
        - name: id
          in: query
          description: ID of the customer to fetch
          required: true
          style: form
          explode: false
          schema:
            type: array
            items:
              type: integer
```

and with the request `?id=1,2,3`

It generates then following error:

```
SyntaxError: Unexpected token , in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseObject (C:\Users\P772381\Work\cm-ods-api\node_modules\swagger-express-middleware\lib\helpers\json-schema.js:501:24)
    at JsonSchema.parse (C:\Users\P772381\Work\cm-ods-api\node_modules\swagger-express-middleware\lib\helpers\json-schema.js:92:14)
    at parseParameter (C:\Users\P772381\Work\cm-ods-api\node_modules\swagger-express-middleware\lib\param-parser.js:143:35)
    at C:\Users\P772381\Work\cm-ods-api\node_modules\swagger-express-middleware\lib\param-parser.js:35:35
    at Array.forEach (<anonymous>)
    at parseSimpleParams (C:\Users\P772381\Work\cm-ods-api\node_modules\swagger-express-middleware\lib\param-parser.js:30:12)
    at Layer.handle [as handle_request] (C:\Users\P772381\Work\cm-ods-api\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\P772381\Work\cm-ods-api\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\P772381\Work\cm-ods-api\node_modules\express\lib\router\index.js:284:7 status: undefined, toJSON: [Function: errorToJSON] }
```

The error is a result of the following line: https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/lib/param-parser.js#L35

```js
        req.query[param.name] = parseParameter(param, req.query[param.name], param);
```

needs to be 

```js
        req.query[param.name] = parseParameter(param, req.query[param.name], param.schema);
```
